### ISSUE TITLE
CI/CD 구축 과정

### ISSUE THREAD

**Issue by InyongHwang** [InyongHwang/HotDeal#4]
1. EC2 서버 구매
    - Host : 54.180.71.246
    - Username : ubuntu
---
2. EC2 서버에서 docker 설치
    - #3 
---
3. docker hub 가입
    - DOCKER_USERNAME : 도커 허브 가입시 작성한 username (이메일 아님)
    - DOCKER_PASSWORD : 도커 허브 가입시 작성한 password
---
4. spring boot 프로젝트 생성
    - `build.gradle`에 아래 코드 추가

        ```java
        // 스프링 부트 2.5.0 버전 이상일 경우, plain.jar가 자동 생성되는 것을 비활성화
        jar {
            enabled = false
        }

        // build시 app.jar로 jar파일이 생성됨
        bootJar{
            archivesBaseName = 'app'
            archiveFileName = 'app.jar'
            archiveVersion = "0.0.0"
        }
        ```

    - 프로젝트의 루트 경로(src 디렉토리와 동일한 경로)에 `Dockerfile` 생성

        ![image](https://github.com/InyongHwang/HotDeal/assets/123296558/3e522c53-9857-4dab-bbbe-24f2dfc66804)

        ```java
        FROM openjdk:17-jdk-slim-buster 
        ARG JAR_FILE=build/libs/*.jar
        COPY ${JAR_FILE} app.jar
        ENTRYPOINT ["java","-jar","/app.jar"]
        ```
        * Openjdk를 이용하여 타겟 디렉터리(`build/libs`)의 `jar`를 Docker 컨테이너에 `app.jar`로 넣고 실행한다는 의미

    - github의 spring boot 프로젝트 레포지토리에 commit & push
---
5. Github Action Workflow 생성
    - github의 sprint boot 프로젝트 레포지토리에서 Actions 클릭

        ![image](https://github.com/InyongHwang/HotDeal/assets/123296558/2cbfa978-a123-4d14-a7bb-59990bee0410)

    - Java with Gradle 클릭
    
        ![image](https://github.com/InyongHwang/HotDeal/assets/123296558/ed950133-2d50-408e-b3a1-928b6c29e09e)

    - 프로젝트 루트 경로의 `.github/`에 `.github/workflows/gradle.yml` 가 자동 생성되며 아래와 같이 작성

        ```yml
        # This workflow uses actions that are not certified by GitHub.
        # They are provided by a third-party and are governed by
        # separate terms of service, privacy policy, and support
        # documentation.
        # This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
        # For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

        name: Java CI with Gradle

        on:
          push:
            branches: [ "master" ]
          pull_request:
            branches: [ "master" ]
        
        permissions:
          contents: read

        jobs:
          build:

            runs-on: ubuntu-latest

            steps:
            - uses: actions/checkout@v3
            - name: Set up JDK 17
              uses: actions/setup-java@v3
              with:
                java-version: '17'
                distribution: 'temurin'
            
            ## gradlew 실행 권한 부여
            - name: Grant execute permission for gradlew
              run: chmod +x gradlew
            
            ## spring boot 프로젝트 jar 파일 빌드
            - name: Build with Gradle
              run: ./gradlew build
        ```

    - push하고 Actions 탭으로 이동하면 자동으로 프로젝트 테스트 및 빌드 진행
        
        ![image](https://github.com/InyongHwang/HotDeal/assets/123296558/98b9cbcd-9f32-442e-997b-5a3f309b4be7)
---
6. github Actions workflow : Docker에 이미지 push하고 Build 과정 추가
    - spring boot 프로젝트 레포지토리의 Settings 탭으로 이동
    
        ![image](https://github.com/InyongHwang/HotDeal/assets/123296558/f6df88d0-0445-40a6-8b05-47e8b3c9dc4a)

    - 좌측의 Settings 세부 항목 중 `Security`에서 `Secrets and variables/Actions` 클릭

        ![image](https://github.com/InyongHwang/HotDeal/assets/123296558/7b41f44a-6d5b-43be-b8f6-096317596b32)

    - `New repository secret` 클릭하여 docker hub가입시 작성한 `DOCKER_USERNAME`(이메일 아님)과 `DOCKER_PASSWORD` 추가

        ![image](https://github.com/InyongHwang/HotDeal/assets/123296558/e5594886-0a8f-4a74-ad8f-20376f538c9d)

    - `.github/workflows/gradle.yml` 하단에 추가 작성 (hotdeal-cicd는 도커 이미지명으로, 사용자가 원하는대로 지정해도 됨)
    
        ```yml
        ## Docker Hub에 이미지 push하고 Docker build 하기
        - name: Docker build
          run: |
            docker login -u ${{ secrets.DOCKER_USERNAME }} -p {{ secrets.DOCKER_PASSWORD }}
            docker build -t hotdeal-cicd .
            docker tag hotdeal-cicd ${{ secrets.DOCKER_USERNAME }}/hotdeal-cicd:${GITHUB_SHA::7}
            docker push ${{ secrets.DOCKER_USERNAME }}/hotdeal-cicd:${GITHUB_SHA::7}
        ```
---
7. github Actions workflow : Docker Hub에 push한 이미지를 자동으로 EC2 서버에 받아와서 run 과정 추가
    - ssh-key 생성 : spring boot 프로젝트의 루트 경로에서 terminal에 다음과 같이 입력
        ```bash
        ssh-keygen -t rsa -b 4096 -C "[내이메일]" -f hotdeal-cicd
        ```
    
    - 공개키(`hotdeal-cicd.pub`)를 EC2 서버의 `~/.ssh/authorized_keys`에 붙여넣기

    - 개인키(`hotdeal-cicd`)를 `DOCKER_USERNAME`과 같이 `secrets`에 등록
        
        ![image](https://github.com/InyongHwang/HotDeal/assets/123296558/463ba993-c79a-4ffc-a758-4cacd8c94fbf)

    - `.github/workflows/gradle.yml` 하단에 추가 작성
    
        ```yml
        ## Docker Hub에 push한 이미지를 자동으로 EC2 서버에 받아와서 run 하기
        - name: Deploy
          uses: appleboy/ssh-action@master
          with:
            host: 54.180.71.246 ## (EC2 서버의 host)
            username: ubuntu ## (EC2 서버의 username)
            key: ${{ secrets.PRIVATE_KEY }}
            env: GITHUB_SHA
            script: |
              docker pull ${{ secrets.DOCKER_USERNAME }}/hotdeal-cicd:${GITHUB_SHA::7}
              docker tag ${{ secrets.DOCKER_USERNAME }}/hotdeal-cicd:${GITHUB_SHA::7} hotdeal-cicd
              docker stop server
              docker run -d --rm --name server -p 80:8080 hotdeal-cicd
        ```
